[tool]
[project]
name = "humlab-westac"
version = "0.5.40"
description = "Welfare State Analytics"
authors = [{ name = "Roger Mähler", email = "roger.mahler@hotmail.com" }]
classifiers = [
    'Operating System :: OS Independent',
    'Topic :: Software Development',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.12',
]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "bokeh",
    "click",
    "ipywidgets",
    "jupyterlab==3.*",
    "loguru>=0.5.3,<0.6.0",
    "matplotlib",
    "msgpack>=1.0.2,<2.0.0",
    "nltk",
    "pandas>=2.1.0,<3.0.0",
    "pandas-bokeh",
    "scikit-learn",
    "scipy",
    "tqdm",
    "ipydatagrid>=1.1.8,<2.0.0",
    "bqplot>=0.12.32,<0.13.0",
    "PyGithub>=1.55,<2.0.0",
    "plotly>=5.5.0,<6.0.0",
    "bar-chart-race>=0.1.0,<0.2.0",
    "urllib3==1.26.15",
    "humlab-penelope[full]>=0.8.4",
]

[project.urls]
Homepage = "https://westac.se"
Repository = "https://github.com/welfare-state-analytics/welfare_state_analytics"

[project.scripts]
parlaclarin-vectorize = "scripts.riksdagens_protokoll.parlaclarin.vectorize:process"

# FIXME: #137 Remove redundant dependencies

[dependency-groups]
dev = [
    "black",
    "coverage",
    "flake8",
    "flake8-pytest-style",
    "invoke",
    "isort",
    "mypy",
    "nbstripout",
    "pep8-naming",
    "pre-commit",
    "pycodestyle",
    "pyflakes",
    "pylint",
    "pytest",
    "pytest-cov",
    "rope",
    "yapf",
    "debugpy",
    "pyinstrument",
    "jupytext",
    "xeus-python",
    "tomlkit",
    "jupyterlite",
    "pyright",
    "pytest-mock>=3.12.0,<4.0.0",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "-rfE",
    "-q",
    # "-s",
]
log_cli = "false"
testpaths = ["tests"]
norecursedirs = [
    'notebooks',
    '.git',
    'data',
    "test_data",
    'output',
    'deprecated',
    '__pycache__',
    'tmp',
]
python_files = "*_test.py"
python_functions = "test_*"
filterwarnings = [
    "ignore::_pytest.warning_types.PytestCollectionWarning",
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
    "ignore::RuntimeWarning",
    "ignore::UserWarning",
]
markers = [
    "long_running: takes time to run",
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

[tool.black]
line-length = 120
target-version = ["py312"]
skip-string-normalization = true
# include = '\.pyi?$'
exclude = '''
(
  \.git
  | \.pypy_cache
  | \.pytest_cache
  | \.ipynb_checkpoints
  | deprecated
)
'''

[tool.isort]
# https://github.com/timothycrosley/isort/wiki/isort-Settings
profile = "black"
line_length = 120
py_version = "auto"
float_to_top = true
src_paths = ["notebooks", "westac", "tests", "scripts"]
extra_standard_library = ["__paths__"]

[tool.coverage]
# https://github.com/nedbat/coveragepy

[tool.coverage.run]
source = ["notebooks", "westac"]
branch = true
omit = ['**/__init__.py', '**/__paths__.py']

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
show_missing = true
sort = "Name"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["notebooks*", "westac*", "scripts*"]
